### ISSUE TITLE
Build for 1.15.1 fails

### ISSUE THREAD

**Issue by Bayside308** [okyanus-mc/runtime#12]
Okyanus fails to build for 1.15.1. Is there a way to make this work? It appears that your maven site is down.

Updated `gradle.properties` file:

```# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.15.1
	yarn_mappings=1.15.1+build.14
	loader_version=0.7.2+build.175

# Mod Properties
	mod_version = 0.2.0-SNAPSHOT
	maven_group = club.issizler.okyanus
	archives_base_name = okyanus
```

Error:

```
* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':fatJar'.
   > Could not resolve club.issizler.okyanus:api:0.2.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve club.issizler.okyanus:api:0.2.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.issizler.club/club/issizler/okyanus/api/0.2.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://maven.issizler.club/club/issizler/okyanus/api/0.2.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://maven.issizler.club/club/issizler/okyanus/api/0.2.0-SNAPSHOT/maven-metadata.xml'.
                  > maven.issizler.club
```

**Comment by Admicos** [comment]
Yeah, I kinda abandoned this a few months ago. You should be able to overwrite the Maven repo by [creating a local workspace](https://okyanus-mc.github.io/dev/okyanus/workspace.html), but I haven't tested the code itself, it might break, and you probably won't get any support on that.

**Comment by Bayside308** [comment]
I created my own local workspace and now I get a new error.

Error:

```
> Configure project :
Fabric Loom: 0.2.4-SNAPSHOT Build(jenkins #10)
:setting up loom dependencies
:setting up mappings (yarn 1.15.1+build.14)
:providing net.fabricmc:fabric-loader:0.7.2+build.175 (net.fabricmc.yarn.1_15_1.14)
:providing net.fabricmc:fabric-loader:0.7.2+build.175 (net.fabricmc.yarn.1_15_1.14) sources

> Task :compileJava FAILED
:setting java compiler args
Could not find refmap definition, will be using default name: runtime-refmap.json
Note: SpongePowered MIXIN Annotation Processor Version=0.8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.AbstractMethodError: Receiver class net.fabricmc.loom.mixin.ObfuscationServiceFabric does not define or inherit an implementation of the resolved method abstract getObfuscationTypes(Lorg/spongepowered/tools/obfuscation/interfaces/IMixinAnnotationProcessor;)Ljava/util/Collection; of interface org.spongepowered.tools.obfuscation.service.IObfuscationService.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
```

I hope you'll pick up this project again! I'd love to contribute (by making plugins).

**Comment by Admicos** [comment]
Try updating fabric-loom as well. The older version of loom used by this probably doesn't support 1.15.

> I hope you'll pick up this project again! I'd love to contribute (by making plugins).

Yeah, I kinda abandoned _Minecraft development_ in itself, so I'm not entirely sure if this will ever pick back up. However, feel free to fork and update yourself, if you're willing to.

**Comment by Bayside308** [comment]
I updated Loom to 0.2.5-SNAPSHOT (the latest release) and it still fails but with a new error. I also tried 0.2.6-SNAPSHOT (a dev build), but it also fails with the same error.

```
> Configure project :
Fabric Loom: 0.2.5-SNAPSHOT Build(jenkins #23)
:setting up loom dependencies
:setting up mappings (yarn 1.15.1+build.14)
:providing net.fabricmc:fabric-loader:0.7.2+build.175 (net.fabricmc.yarn.1_15_1.14)
:providing net.fabricmc:fabric-loader:0.7.2+build.175 (net.fabricmc.yarn.1_15_1.14) sources

> Task :compileJava FAILED
:setting java compiler args
Could not find refmap definition, will be using default name: runtime-refmap.json
java.lang.ClassNotFoundException: net.minecraft.util.SystemUtil
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at net.fabricmc.loom.mixin.MixinMappingProviderTiny.getMethodMapping(MixinMappingProviderTiny.java:54)
        at org.spongepowered.tools.obfuscation.ObfuscationEnvironment.getObfMethod(ObfuscationEnvironment.java:227)
        at org.spongepowered.tools.obfuscation.ObfuscationEnvironment.getObfMethod(ObfuscationEnvironment.java:214)
        at org.spongepowered.tools.obfuscation.ObfuscationDataProvider.getRemappedMethod(ObfuscationDataProvider.java:206)
        at org.spongepowered.tools.obfuscation.ObfuscationDataProvider.getObfMethod(ObfuscationDataProvider.java:194)
        at org.spongepowered.tools.obfuscation.ObfuscationDataProvider.getObfEntry(ObfuscationDataProvider.java:128)
        at org.spongepowered.tools.obfuscation.ObfuscationDataProvider.getObfEntryRecursive(ObfuscationDataProvider.java:69)
        at org.spongepowered.tools.obfuscation.ObfuscationDataProvider.getObfMethodRecursive(ObfuscationDataProvider.java:152)
        at org.spongepowered.tools.obfuscation.AnnotatedMixinElementHandlerInjector.remapReference(AnnotatedMixinElementHandlerInjector.java:357)
        at org.spongepowered.tools.obfuscation.AnnotatedMixinElementHandlerInjector.registerInjectionPoint(AnnotatedMixinElementHandlerInjector.java:278)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.registerInjectionPoint(AnnotatedMixin.java:392)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.registerInjector(AnnotatedMixin.java:372)
        at org.spongepowered.tools.obfuscation.AnnotatedMixins.registerInjector(AnnotatedMixins.java:496)
        at org.spongepowered.tools.obfuscation.MixinObfuscationProcessorInjection.processInjectors(MixinObfuscationProcessorInjection.java:107)
        at org.spongepowered.tools.obfuscation.MixinObfuscationProcessorInjection.process(MixinObfuscationProcessorInjection.java:74)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.process(NonIncrementalProcessor.java:45)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:977)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:893)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1219)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1331)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:89)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:49)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:110)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:106)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:59)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:43)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:153)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:835)
Note: SpongePowered MIXIN Annotation Processor Version=0.8
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading named:intermediary mappings from /Users/admin/.gradle/caches/fabric-loom/mappings/net.fabricmc.yarn-tiny-1.15.1-14
/Users/admin/Downloads/Okyanus/runtime/src/main/java/club/issizler/okyanus/runtime/mixin/events/MinecraftDedicatedServerMixin.java:22: warning: Cannot find method mapping for @At(INVOKE.<target>) 'net.minecraft.util.SystemUtil.getMeasuringTimeNano()J'
    @Inject(at = @At(value = "INVOKE", target = "net.minecraft.util.SystemUtil.getMeasuringTimeNano()J", ordinal = 1), method = "setupServer")
    ^
Note: Writing refmap to /Users/admin/Downloads/Okyanus/runtime/build/classes/java/main/runtime-refmap.json
Note: Writing refmap to /Users/admin/Downloads/Okyanus/runtime/build/classes/java/main/runtime-refmap.json
Note: Writing named:intermediary output TinyMappings to /Users/admin/Downloads/Okyanus/runtime/build/loom-cache/mixin-map-1.15.1-14.tiny
Note: Writing refmap to /Users/admin/Downloads/Okyanus/runtime/build/classes/java/main/runtime-refmap.json
Note: Writing refmap to /Users/admin/Downloads/Okyanus/runtime/build/classes/java/main/runtime-refmap.json
Note: Writing named:intermediary output TinyMappings to /Users/admin/Downloads/Okyanus/runtime/build/loom-cache/mixin-map-1.15.1-14.tiny
/Users/admin/Downloads/Okyanus/runtime/src/main/java/club/issizler/okyanus/runtime/mixin/events/ServerPlayNetworkHandlerMixin$MoveEvent.java:37: error: x has private access in Entity
            double x = this.player.x;
                                  ^
/Users/admin/Downloads/Okyanus/runtime/src/main/java/club/issizler/okyanus/runtime/mixin/events/ServerPlayNetworkHandlerMixin$MoveEvent.java:38: error: y has private access in Entity
            double y = this.player.y;
                                  ^
/Users/admin/Downloads/Okyanus/runtime/src/main/java/club/issizler/okyanus/runtime/mixin/events/ServerPlayNetworkHandlerMixin$MoveEvent.java:39: error: z has private access in Entity
            double z = this.player.z;
                                  ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by Admicos** [comment]
Yeah, for that you'll need to update the mixin code. Specifically the following files and lines:

- `events/MinecraftDedicatedServerMixin.java:22`
- `events/ServerPlayNetworkHandlerMixin$MoveEvent.java:37` to `39`

**Comment by Bayside308** [comment]
Thank you for your continued help! I’ve fixed up `$MoveEvent` but I’m not entirely sure what to do for the other file.

**Comment by Admicos** [comment]
The errors are these:

```
java.lang.ClassNotFoundException: net.minecraft.util.SystemUtil

...

/Users/admin/Downloads/Okyanus/runtime/src/main/java/club/issizler/okyanus/runtime/mixin/events/MinecraftDedicatedServerMixin.java:22: warning: Cannot find method mapping for @At(INVOKE.<target>) 'net.minecraft.util.SystemUtil.getMeasuringTimeNano()J'
```

The most likely reason is that Yarn renamed the SystemUtil class to something else.

It seems like https://github.com/FabricMC/yarn/pull/930 renames it to just `Util`, so you might want to start from there.

**Comment by Bayside308** [comment]
I fixed the compilation errors and it compiles, but when executed with `java -Xmx1G -jar okyanus-1.15.1-0.2.0-SNAPSHOT.jar`, I get `no main manifest attribute, in okyanus-1.15.1-0.2.0-SNAPSHOT.jar`. I understand what this error is, but which class would be the main class for the manifest?

**Comment by Admicos** [comment]
This is a Fabric Loader mod, not a server jar. While it was a server jar when it began, it's not anymore.
